apiVersion: apps/v1
kind: Deployment
metadata:
  name: stack-deployment
  labels:
    app: eureka-server
spec:
  replicas: 5
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: "nandolup/eureka-server"
          ports:
            - name: http
              containerPort: 80
      tolerations:
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 2
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 2
